language: python
python:
  - "2.7"
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.0/elasticsearch-2.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.0.deb && sudo service elasticsearch restart
  - npm install -g grunt-cli
install:
  - pip install -U -r requirements.txt
  - python setup.py develop
  - pushd openfda/spl && npm install && popd
  - pushd api/faers && npm install && popd
services:
  - elasticsearch
before_script:
  - sleep 10
script:
  - python setup.py test
  - pushd api/faers && npm test && popd
