language: python
python:
  - "2.7"
before_install:
  - npm install -g grunt-cli
install:
  - pip install -U -r requirements.txt
  - python setup.py develop
  - pushd api/faers && npm install && popd
script:
  - python setup.py test
  - pushd api/faers && npm test && popd
