version: '3'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.13
    environment:
      - xpack.security.enabled=false
    ports:
      - "9200"
  api:
    build: ./api/faers
    environment:
      - ES_HOST=es:9200
    depends_on:
      - es
    ports:
      - 8000:8000
  pipeline:
    build: .
    environment:
      - ES_HOST=es:9200
    depends_on:
      - es
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
